version: '3.4'

services:
  dockerweb:
    image: ${DOCKER_REGISTRY-}dockerweb
    build:
      context: .
      dockerfile: DockerWeb/Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - dockerwebdbservice
    networks:
      - dockerweb-net
    environment:
      ServiceHost: "dockerwebdbservice"

  dockerwebdbservice:
    image: ${DOCKER_REGISTRY-}dockerwebdbservice
    build:
      context: .
      dockerfile: DockerWebDbService/Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      DefaultConnection: "Host=db;Port=5432;Username=postgres;Password=password;Database=DockerWebApiDB;"
    networks:
      - dockerweb-net

  db:
    container_name: dockerweb_db
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "DockerWebDB"
    networks:
      - dockerweb-net
    volumes:
      - type: volume
        source: webapidb-data
        target: /var/lib/postgresql/data
networks:
  dockerweb-net:
    driver: bridge
volumes:
   webapidb-data: