version: '3.4'

services:
  dockerwebdbservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:5002"

  dockerweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:5003"
